version: build{build}

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
#    - PYTHON: "C:\\Python36-x64"
#      PYTHON_VERSION: "3.6.7"
#      PYTHON_ARCH: "64"
  
    
clone_folder: c:\dev\lxpapi

install:
  - SET PATH=C:\\Python36-x64;C:\\Python36-x64\\Scripts;%PATH%

before_build:
  - cd c:\dev\lxpapi
  - pip install click
  - pip install keyring
  - pip install requests
  - pip install pyinstaller
  
build_script:
  - pyinstaller -F LxpApi\\lxpservice.py
 
artifacts:
  - path: lxpservice.exe

deploy:
  description: 'Latest lxpservice Release'
  provider: GitHub
  auth_token:
    secure: WEV9mRJC/pC2HFqJMXbLzEfBXAHu8aGDFIR8ARSip9n6jDJyCz3KstjSPM4VsgKc
  artifact: /.*/
  draft: false
  prerelease: false
  force_update: true
  on:
    branch: appvoyer              # release from master branch only
